{{ if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "traefik-certmanager.serviceAccountName" . }}
  labels:
    {{- include "traefik-certmanager.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups: ["traefik.containo.us"]
  resources: ["ingressroutes"]
  verbs: ["watch", "patch"]
- apiGroups: ["traefik.io"]
  resources: ["ingressroutes"]
  verbs: ["watch", "patch"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates"]
  verbs: ["get", "create", "delete"]
- apiGroups: [""]
  resources: ["configmaps", "leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
{{ end }}
