{{ if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "traefik-certmanager.fullname" . }}
  labels:
    {{- include "traefik-certmanager.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "traefik-certmanager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "traefik-certmanager.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
