# code: language=yaml
---
name: lint_static_checks

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: install_tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy

      - name: isort_check
        run: isort --check-only --diff .

      - name: black_check
        run: black --check .

      - name: flake8_check
        run: flake8 .

      - name: mypy_check
        run: mypy .
